/******************************************************************************/
/****        Generated by IBExpert 2015.12.21.1 15/12/2023 17:47:45        ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

CREATE DATABASE 'LOCALHOST:C:\Projeto01\TeckSystem\BD\BDTK.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 8192
DEFAULT CHARACTER SET NONE;



/******************************************************************************/
/****                              Generators                              ****/
/******************************************************************************/

CREATE GENERATOR GENIDLISTA;
SET GENERATOR GENIDLISTA TO 7;

CREATE GENERATOR GENIDTAREFAS;
SET GENERATOR GENIDTAREFAS TO 13;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE LISTATAREFAS (
    ID         INTEGER NOT NULL,
    DESCRICAO  VARCHAR(50),
    STATUS     VARCHAR(20)
);

CREATE TABLE TAREFAS (
    ID               INTEGER NOT NULL,
    ID_LISTA         INTEGER,
    TITULO           VARCHAR(50),
    DESCRICAO        VARCHAR(200),
    DATA_CADASTRO    DATE,
    DATA_CONCLUSAO   DATE,
    DATA_VENCIMENTO  DATE,
    STATUS           VARCHAR(20)
);



/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE LISTATAREFAS ADD CONSTRAINT PK_LISTATAREFAS PRIMARY KEY (ID);
ALTER TABLE TAREFAS ADD CONSTRAINT PK_TAREFAS PRIMARY KEY (ID);


/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/

ALTER TABLE TAREFAS ADD CONSTRAINT FK_TAREFAS_1 FOREIGN KEY (ID_LISTA) REFERENCES LISTATAREFAS (ID);
